config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check

  root "home#index"

  resources :tweets, only: :create do
    resources :likes, only: [:create, :destroy]
    resources :bookmarks, only: [:create, :destroy]
    resources :retweets, only: [:create, :destroy]
  end
  resources :usernames, only: [:new, :update]
  get :dashboard, to: "dashboard#index"

  resources :likes, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :user_id, uniqueness: { scope: :tweet_id }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet, counter_cache: :likes_count
  belongs_to :user

  validates :user_id, uniqueness: { scope: :tweet_id }
end

app/models/retweet.rb
class Retweet < ApplicationRecord
  belongs_to :user
  belongs_to :tweet, counter_cache: :retweets_count

  validates :user_id, uniqueness: { scope: :tweet_id }
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  validates :body, presence: :true, length: { maximum: 280 }
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarked_users, through: :bookmarks, source: :user
  has_many :retweets, dependent: :destroy
  has_many :retweeted_users, through: :retweets, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarked_tweets, through: :bookmarks, source: :tweet
  has_many :retweets, dependent: :destroy
  has_many :retweeted_tweets, through: :retweets, source: :tweet

  has_one_attached :avatar
  validates :username, uniqueness: { case_sensitive: false}, allow_blank: true

  before_save :set_display_name, if: -> { username.present? && display_name.blank? }
  def set_display_name
    self.display_name = username.humanize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :redirect_to_username_form, if: -> {user_signed_in? && current_user.username.blank? }

  protected

  def after_sign_in_path_for(resource)
    dashboard_path
  end

  def redirect_to_username_form
    return if controller_name =="usernames"
    redirect_to new_username_path
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!

  def create
    @bookmark = current_user.bookmarks.create(tweet: tweet )
    respond_to do |format|
      format.html { redirect_to dashboard_path }
      format.turbo_stream
    end
  end

  def destroy
    @bookmark = tweet.bookmarks.find(params[:id])
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_path }
      format.turbo_stream
    end
  end

  private
  def tweet
    @tweet ||= Tweet.find(params[:tweet_id])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
    @tweets = Tweet.includes(:liked_users, :bookmarked_users, :retweeted_users,  :user).order(created_at: :desc).map do |tweet| 
      TweetPresenter.new(tweet: tweet, current_user: current_user) 
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to dashboard_path if user_signed_in?
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = current_user.likes.create(tweet: tweet )
    respond_to do |format|
      format.html { redirect_to dashboard_path }
      format.turbo_stream
    end
  end

  def destroy
    @like = tweet.likes.find(params[:id])
    @like.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_path }
      format.turbo_stream
    end
  end

  private
  def tweet
    @tweet ||= Tweet.find(params[:tweet_id])
  end
end

app/controllers/retweets_controller.rb
class RetweetsController < ApplicationController
  before_action :authenticate_user!

  def create
    @retweet = current_user.retweets.create(tweet: tweet )
    respond_to do |format|
      format.html { redirect_to dashboard_path }
      format.turbo_stream
    end
  end

  def destroy
    @retweet = tweet.retweets.find(params[:id])
    @retweet.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_path }
      format.turbo_stream
    end
  end

  private
  def tweet
    @tweet ||= Tweet.find(params[:tweet_id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  def create
    @tweet = Tweet.new(tweet_params.merge(user: current_user))

    if @tweet.save
      respond_to do |format|
        format.html { redirect_to dashboard_path }
        format.turbo_stream 
      end
    end
  end
  private
  
  def tweet_params
    params.require(:tweet).permit(:body)
  end
end

app/controllers/usernames_controller.rb
class UsernamesController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :redirect_to_username_form 
  def new
  end

  def update
    if username_params[:username].present? && current_user.update(username_params)
      flash[:notice] = "Username successfully updated."
      redirect_to dashboard_path
    else
      flash[:alert] = if username_params[:username].blank?
                        "Please set a username"
                      else
                        current_user.errors.full_messages.join(", ")
                      end
      redirect_to new_username_path
    end
  end

  private

  def username_params
    params.require(:user).permit(:username, :display_name, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.slim
.col-6
  .mb-3
    =link_to "Home", dashboard_path, class: "fs-4 text-decoration-none text-black fw-semibold"
  .mb-4
    =render "shared/tweet_form"
  #tweets
      = render partial: "tweets/tweet", collection: @tweets, as: :tweet_presenter
.col Column
        

app/views/home/index.html.slim
- if user_signed_in?
  h1 Hello
  = current_user.email
  br
  = link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "btn btn-outline-danger"
  = form_with model: Tweet.new, url: tweets_path, local: :true do |f|
    =f.text_field :body
    =f.submit

  - Tweet.find_each do |tweet|
    =tweet.body
-else
  h1 Hello World
  
  =link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg m-2"
  =link_to "Log in", new_user_session_path, class: "btn btn-outline-primary btn-lg m-2"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | TwitterClone
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
    = favicon_link_tag asset_path('twitter.png') 
  body
    - if flash.any?
      = render "shared/flashes"
    - if user_signed_in?
      -if controller_name == "usernames"
        =yield
      -else
        .container.py-2
          .row
            =render "shared/sidebar"
            = yield

    -else
      =yield

app/views/retweets/create.turbo_stream.slim
=turbo_stream.replace dom_id(@tweet) do 
  =render partial: "tweets/tweet", locals: { tweet_presenter: TweetPresenter.new(tweet: @tweet, current_user: current_user) }

app/views/retweets/destroy.turbo_stream.slim
=turbo_stream.replace dom_id(@tweet) do
  =render partial: "tweets/tweet", locals: { tweet_presenter: TweetPresenter.new(tweet: @tweet, current_user: current_user) }

app/views/shared/_flashes.html.slim
-if notice
  .alert.alert-info.alert-dismissible.fade.show.rounded-0.text-center role="alert"
    =notice 
    button.btn-close role="button" data-bs-dismiss="alert" aria-label="Close"
      / span aria-hidden="true" &times;

-if alert 
  .alert.alert-warning.alert-dismissible.fade.show.rounded-0.text-center role="alert"
    =alert
    button.btn-close role="button" data-bs-dismiss="alert" aria-label="Close"
      / span aria-hidden="true" &times;

app/views/shared/_sidebar.html.slim
aside.side-navbar.col
  =link_to root_path, class: "d-flex align-items-center fs-2 mb-2 mb-2", id: "twitter-logo-link" do
    .px-2.py-2.rounded-circle
      i.bi.bi-twitter.mx-3.my-4.twitter-text-blue
  =link_to root_path, class: "d-flex align-items-center fs-5 mb-2 text-primary" do
    .px-4.py-2.rounded-pill 
      i.bi.bi-house.me-4.mb-3
      |  Home
  =link_to root_path, class: "d-flex align-items-center fs-5 mb-2 text-primary" do 
    .px-4.py-2.rounded-pill 
      i.bi.bi-hash.me-4.mb-3
      |  Explore
  =link_to root_path, class: "d-flex align-items-center fs-5 mb-2 text-primary" do 
    .px-4.py-2.rounded-pill 
      i.bi.bi-bell.me-4.mb-3 
      |  Notifications
  =link_to root_path, class: "d-flex align-items-center fs-5 mb-2 text-primary" do 
    .px-4.py-2.rounded-pill 
      i.bi.bi-chat-dots.me-4.mb-3 
      |  Messages
  =link_to root_path, class: "d-flex align-items-center fs-5 mb-2 text-primary" do 
    .px-4.py-2.rounded-pill 
      i.bi.bi-bookmark.me-4.mb-3 
      |  Bookmarks
  =link_to root_path, class: "d-flex align-items-center fs-5 mb-4 text-primary" do 
    .px-4.py-2.rounded-pill 
      i.bi.bi-person.me-4.mb-3 
      |  Profile
  .d-flex.align-items-center.fs-6.text-primary.py-2
    =button_tag "Tweet", class: "btn btn-twitter btn-lg mx-2 w-100 rounded-pill", data: { "bs-toggle": "modal", "bs-target": "#exampleModal" }
  .d-flex.align-items-center.fs-6.text-primary.py-2
    = link_to "Log Out", destroy_user_session_path, data: { turbo_method: :delete }, class: "twitter-link"

  #exampleModal.modal.fade[tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"]
    .modal-dialog[role="document"]
      .modal-content
        .modal-header.border-bottom-0
          button.btn.btn-close.mx-0[type="button" data-bs-dismiss="modal" aria-label="Close" id="close-modal-button"]

        .modal-body
          =render "shared/tweet_form"

app/views/shared/_tweet_form.html.slim
= form_with model: Tweet.new, url: tweets_path, method: :post, data: { controller: 'tweet-form'}, class: "w-100" do |f|
  =f.text_area :body, placeholder: "What's heppening?", class: "form-control tweet-input w-100 mb-4"
  .d-flex.justify-content-end
    =f.submit class: "btn btn-lg btn-twitter rounded-pill"

app/views/tweets/_tweet.html.slim
=turbo_frame_tag dom_id(tweet_presenter.tweet)
  .py-3.px-2.d-flex.tweet
    .flex-shrink-0
      = image_tag  tweet_presenter.avatar, size: 40, class: "img-fulid rounded-circle"
    .flex-grow-1.ms-3
      p.mb-0
        span.fw-bolder
          =tweet_presenter.display_name
        span.text-muted
          |  @
          =tweet_presenter.username
          |  - 
        span.text-muted
          =tweet_presenter.created_at
      p.mb-0
        =tweet_presenter.body
      .d-flex.justify-content-between.action-links.views
        div
          =link_to "#", class: "text-decoration-none text-black views" do 
            i.bi.bi-eye
            span  Views
        div
          =link_to "#", class: "text-decoration-none text-black replies" do
            i.bi.bi-chat 
            span  Replies
        div
            =link_to tweet_presenter.retweet_tweet_url, data: { "turbo-method": tweet_presenter.turbo_retweet_data_method }, class: "text-decoration-none text-black likes" do
              i[class="bi bi-share#{tweet_presenter.retweet_icon}"]
              span
                |
                =tweet_presenter.retweets_count
                |  
                =tweet_presenter.retweet_text
        div
            =link_to tweet_presenter.like_tweet_url, data: { "turbo-method": tweet_presenter.turbo_like_data_method }, class: "text-decoration-none text-black likes" do
              i[class="bi bi-heart#{tweet_presenter.like_heart_icon}"]
              span
                |  
                =tweet_presenter.likes_count
        div
            =link_to tweet_presenter.bookmark_tweet_url, data: { "turbo-method": tweet_presenter.turbo_bookmark_data_method }, class: "text-decoration-none text-black likes" do
              i[class="bi bi-bookmark#{tweet_presenter.bookmark_icon}"]
              span
                |  
                =tweet_presenter.bookmark_text

app/views/tweets/create.turbo_stream.slim
= turbo_stream.prepend "tweets" do 
  = render partial: "tweets/tweet", locals: { tweet_presenter: TweetPresenter.new(@tweet) }

app/views/usernames/new.html.slim
.container.py-5 style="max-width: 540px"
  h2 New user form

  = form_with model: current_user, local: true, url: username_path(current_user) do |f|
    .mb-3 
      =f.label :username, class: "form-label"
      =f.text_field :username, class: "form-control"
      =f.label :display_name, class: "form-label"
      =f.text_field :display_name, class: "form-control"
      =f.label :avatar, class: "form-label"
      =f.file_field :avatar, class: "form-control"
      =f.submit "Save",  class: "btn btn-twitter rounded-pill my-2"